# Generated by Django 4.1.5 on 2023-04-04 01:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "cpfCnpj",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                ("telefone", models.CharField(max_length=15)),
                ("endereco", models.EmailField(max_length=300)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fabricante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("usuario", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=100)),
                ("endereco", models.EmailField(max_length=300)),
                ("senha", models.CharField(max_length=50)),
                ("telefone", models.CharField(max_length=15)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="cadastrado_em",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("quantidade", models.FloatField(max_length=50)),
                ("valor", models.EmailField(max_length=20)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("cadastrado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.categoria",
                    ),
                ),
                (
                    "fabricante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.fabricante",
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cadastros.fornecedor",
                    ),
                ),
            ],
        ),
    ]
