# Generated by Django 4.1.5 on 2023-04-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cadastros",
            "0003_remove_produto_fabricante_remove_produto_quantidade_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fornecedor",
            name="email",
        ),
        migrations.AlterField(
            model_name="fornecedor",
            name="telefone",
            field=models.CharField(max_length=15, verbose_name="Telefone"),
        ),
    ]
