# Generated by Django 4.1.5 on 2023-04-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0004_remove_fornecedor_email_alter_fornecedor_telefone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="funcionario",
            old_name="senha",
            new_name="funcao",
        ),
        migrations.RemoveField(
            model_name="funcionario",
            name="usuario",
        ),
        migrations.AlterField(
            model_name="funcionario",
            name="endereco",
            field=models.CharField(max_length=300),
        ),
    ]
