# Generated by Django 4.1.5 on 2023-04-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0005_rename_senha_funcionario_funcao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="endereco",
            field=models.CharField(max_length=300),
        ),
    ]
