# Generated by Django 4.1.5 on 2023-08-25 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0007_funcionario_usuario_venda_cadastrado_por"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=9, verbose_name="Quantidade"
            ),
            preserve_default=False,
        ),
    ]
