# Generated by Django 5.0.4 on 2024-05-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0011_carrinho_pedido_produtopedido_delete_venda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='ciclo',
        ),
    ]
