# Generated by Django 5.0.4 on 2024-07-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_remove_produto_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Imagem'),
        ),
    ]
